### ISSUE TITLE
Compilations errors not shown in umbrella project

### ISSUE THREAD

**Issue by pallix** [elixir-lsp/elixir-ls#512]
### Environment

* Elixir & Erlang versions (elixir --version): 

Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
Elixir 1.11.3 (compiled with Erlang/OTP 23)

* Operating system:

Debian 10
 
* Editor or IDE name (e.g. Emacs/VSCode): 

Tested on Emacs 27 and VSCodium 

* Editor Plugin/LSP Client name: lsp-mode, vscodium

### Description of the problem

Compilations errors are not shown in the editor. They appear in the *lsp-log* buffer with a path starting with `lib/....` but are not highlighted on the project. The project is an Elixir umbrella. 

### Troubleshooting

- [ x ] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor => does not help

I can't really send the code since it's closed-source.

The project is rather big so I wonder if there is a problem with the size.

I have tried on a simpler umbrella project and the problem does not appear.

### Logs

1.  If using a client other than VS Code, please try VSCode's "ElixirLS: Elixir support and debugger" extension. Does it reproduce your failure?

Yes.

2.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? If not, please publish a repo on Github that does reproduce it.

Not reproducible with a simpler project.

3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)

I see error of the types

```
** (SyntaxError) lib/...
```

but no highlight of the error in the editor.

**Comment by axelson** [comment]
Hi, umbrella applications are supported so it might be something with your setup. In VSCode are there any javascript warnings (Help->Toggle Developer Tools)?

Do you also not see any warnings in this sample project: https://github.com/elixir-lsp/sample_dialyzer_error_umbrella/tree/compilation-error (make sure you switch to the `compilation-error` branch).

**Comment by pallix** [comment]
The compilation example project works, thank you.

For my project, in the output tab I see this occuring many times per minutes:


```

15:17:47.829 [debug] Tzdata polling shows the loaded tz database is up to date.
[Info  - 3:17:47 PM] Compile took 4397 milliseconds
[Info  - 3:17:47 PM] [ElixirLS WorkspaceSymbols] Updating index...
MIX_ENV: test
MIX_TARGET: 
[Info  - 3:17:48 PM] [ElixirLS WorkspaceSymbols] 2 modules need reindexing
[Info  - 3:17:48 PM] [ElixirLS WorkspaceSymbols] 0 callbacks added to index
[Info  - 3:17:48 PM] [ElixirLS WorkspaceSymbols] 0 types added to index
[Info  - 3:17:48 PM] [ElixirLS WorkspaceSymbols] 2 modules added to index
[Info  - 3:17:48 PM] [ElixirLS WorkspaceSymbols] 14 functions added to index
```

and in the dev console I can only see that:

```
  ERR [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/user/projects/bigproject/.vscode'
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/622cb03f7e070a9670c94bae1a45d78d7181fbd4/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
```

**Comment by axelson** [comment]
Hmm, that dev console error looks unrelated.

A problem like yours is usually fixed with "Stop your editor, remove the entire .elixir_ls directory, then restart your editor". Can you paste a larger snippet of the output tab. It seems really odd for the code to be compiled multiple times if you're not making changes.

**Comment by pallix** [comment]
Thanks for your help. I have tried something different. I removed the .elixir_ls directory but I didn't solve the problem so I tried to opened only one app of the umbrella project and not the whole umbrella directory. The compilation here stops correctly and tzdata do not get polled regularly (this tzdata problem is probably specific to our project!).

However, I can see some of the compilation errors but they are not displayed in the file, only in the elixir ls output.

```
[Info  - 11:09:25 AM] Compile took 1467 milliseconds
[Info  - 11:09:26 AM] [ElixirLS WorkspaceSymbols] 755 modules added to index
[Info  - 11:09:27 AM] [ElixirLS WorkspaceSymbols] 665 types added to index
[Info  - 11:09:43 AM] [ElixirLS WorkspaceSymbols] 11700 functions added to index
[Error - 11:16:41 AM] Request textDocument/documentSymbol failed.
  Message: [DocumentSymbols] Compilation error while parsing source file
  Code: -32000 
MIX_ENV: test
MIX_TARGET: 
Skipping touch on git_version_info.ex
Compiling 8 files (.ex)

** (SyntaxError) lib/abc.ex:413:1: unexpected reserved word: end. The "(" at line 8 is missing terminator ")"
    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
[Info  - 11:16:42 AM] Compile took 502 milliseconds
[Info  - 11:16:42 AM] [ElixirLS WorkspaceSymbols] Updating index...
[Info  - 11:16:42 AM] [ElixirLS WorkspaceSymbols] 0 modules need reindexing
[Info  - 11:16:42 AM] [ElixirLS WorkspaceSymbols] 0 modules added to index
[Info  - 11:16:42 AM] [ElixirLS WorkspaceSymbols] 0 functions added to index
[Info  - 11:16:42 AM] [ElixirLS WorkspaceSymbols] 0 types added to index
[Info  - 11:16:42 AM] [ElixirLS WorkspaceSymbols] 0 callbacks added to index
```

**Comment by lukaszsamson** [comment]
@pallix please post a small repo that reproduces this problem. Otherwise I'm going to close this as umbrellas are working for other users

**Comment by pallix** [comment]
I cant, unfortunately, since it happens only in the big repo of my company.

**Comment by lukaszsamson** [comment]
We don't have resources to chase obscure bugs that cannot be reproduced. If you manage to fix it on your own PRs are always appreciated.

**Comment by pallix** [comment]
I understand. I just hoped somebody would have a similar bug or that the problem could be understood easily. I will reopen the ticket if I find time to get more information.
