### ISSUE TITLE
ElixirLS does not set the MIX_ENV environment variable

### ISSUE THREAD

**Issue by dabaer** [elixir-lsp/elixir-ls#533]
### Environment

* Elixir & Erlang versions (elixir --version):
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
IEx 1.11.4 (compiled with Erlang/OTP 23)

* Operating system: 
RHEL 8.3
* Editor or IDE name (e.g. Emacs/VSCode):
VS Code
* Editor Plugin/LSP Client name:
ElixirLS

### Troubleshooting

- [* ] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [* ] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

The output log for ElixirLS states that it is running under the test MIX_ENV, however that is not the case. The output of `System.get_env("MIX_ENV")` is nil, however my project relies on it heavily, including setting the correct configuration (as the default is DEV, and many variables are not available within elixirls).

How can I make ElixirLS set this environment variable correctly?

**Comment by dabaer** [comment]
A slight addition: I'm running Remote-SSH into a server that is running RHEL 8.3 and the ElixirLS extension. It doesn't seem possible to specify environment variables at all that way to ElixirLS, like you can do with Remote-WSL or local.

**Comment by axelson** [comment]
Where and when are you checking `MIX_ENV`? Is it at compile or runtime? Can you talk more about your setup? I'm not clear if you're running VSCode and ElixirLS both on RHEL 8.3. Are you using the [Visual Studio Code Remote - Containers](https://code.visualstudio.com/docs/remote/containers) extension or something similar?

If you could provide a sample project that shows MIX_ENV not being set to `test` that would be very helpful in tracking down the issue.

**Comment by dabaer** [comment]
I'm checking at compile time (I think, ElixirLS is automatically running dialyzer there). `Mix.env()` does return correctly, however Mix is not available in release environments, so I don't use it. I use the `import Config` method as suggested by the Phoenix docs, and i'm calling System.get_env in the configuration file.

VS Code is running on macOS, however I can reproduce this with my machine running windows. ElixirLS is running on the RHEL machine via the Remote SSH extension.

I will prop up an example project sometime today.

Even running `code .` inside of the Remote-SSH environment does not seem to carry my environment variables as it does if I had run it locally

**Comment by dabaer** [comment]
I've committed https://github.com/dabaer/environmentless_example as a proof of example

**Comment by lukaszsamson** [comment]
@dabaer Note that your project does not work in mix either. It fails to get deps.
```
environmentless_example git:(master) mix deps.get
** (RuntimeError) environment variable MIX_ENV is missing.

    (stdlib 3.14.1) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib 3.14.1) erl_eval.erl:449: :erl_eval.expr/5
    (elixir 1.11.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
    (elixir 1.11.4) lib/config.ex:255: Config.__eval__!/3
    (mix 1.11.4) lib/mix/tasks/loadconfig.ex:49: Mix.Tasks.Loadconfig.load_compile/1
    (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
```
Even if I force it to install deps with `MIX_ENV=dev mix deps.get` the code still does not work with standard mix commands.
```
environmentless_example git:(master) mix compile
** (RuntimeError) environment variable MIX_ENV is missing.

    (stdlib 3.14.1) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib 3.14.1) erl_eval.erl:449: :erl_eval.expr/5
    (elixir 1.11.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
    (elixir 1.11.4) lib/config.ex:255: Config.__eval__!/3
    (mix 1.11.4) lib/mix/tasks/loadconfig.ex:49: Mix.Tasks.Loadconfig.load_compile/1
    (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
environmentless_example git:(master) mix test
** (RuntimeError) environment variable MIX_ENV is missing.

    (stdlib 3.14.1) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib 3.14.1) erl_eval.erl:449: :erl_eval.expr/5
    (elixir 1.11.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
    (elixir 1.11.4) lib/config.ex:255: Config.__eval__!/3
    (mix 1.11.4) lib/mix/tasks/loadconfig.ex:49: Mix.Tasks.Loadconfig.load_compile/1
    (mix 1.11.4) lib/mix/task.ex:394: Mix.Task.run_task/3
```
In my opinion you have some wrong assumptions about `MIX_ENV`. We do not pass environment via this variable, we set it by calling `Mix.env/1` with what comes from `mixEnv` setting in `workspace/didChangeConfiguration` LSP notification. In case of vscode it comes from extension settings and defaults to `test` but you are free to change it.

On the other hand if you would like to do some non standard setup (e.g. set some envs) please refer to readme https://github.com/elixir-lsp/elixir-ls#local-setup

**Comment by NobbZ** [comment]
To be honest, relying on `MIX_ENV` during runtime is as bad as relying on `Mix.env/0`.

Relying on the application environment at runtime would be a saner approach, though when doing this you should also keep the [library guidelines about app env](https://hexdocs.pm/elixir/master/library-guidelines.html#avoid-application-configuration) in mind.

**Comment by dabaer** [comment]
I mostly use MIX_ENV to externally set the environment I want, for example in releases. It's not really related to Mix other than the name.

I will try the suggestions in the Application documentation and see if that doesn't work better. For now though, I made a no-good-terrible-hack and just check if Mix is loaded or not to determine the environment (since dev and test will always have mix).

Appreciate the insights!
